server:
  port: 8091

spring:
  application:
    name: msvc-products
  data.mongodb.uri: mongodb://localhost:27017/productsEcommerce

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka